#!/bin/sh

SCRIPT=$0

function usage() {
    echo "Usage: $SCRIPT JAVA_LOCATION"
    echo ""
    echo "  Activate a Java version for use."
    echo ""
    echo "Arguments:"
    echo "  JAVA_LOCATION  A folder with java and javac."
    echo ""
    echo "Example:"
    echo "  $SCRIPT ~/java/jdk1.8.0_66/bin"
}

if [ $# -eq 0 ]
then
    usage
    return 1
fi

# Parse any arguments passed in.
while [ $# -gt 0 ]
do

    case $1 in

        --help)
            usage
            return 1
            ;;

        *)
            JAVA_LOCATION=$1
            ;;
    esac
    shift

done

# Make sure $JAVA_LOCATION is a directory.
if [ ! -d $JAVA_LOCATION ]
then
    echo "'$JAVA_LOCATION' is not a valid directory."
    usage
    return 1
fi

# Make sure there's a `java` program there.
if [ ! -f $JAVA_LOCATION/java ]
then
    echo "No java at '$JAVA_LOCATION'"
    usage
    return 1
fi

# Make sure there's a `javac` program there.
if [ ! -f $JAVA_LOCATION/javac ]
then
    echo "No javac at '$JAVA_LOCATION'"
    usage
    return 1
fi

export PATH=$JAVA_LOCATION:$PATH
echo "Using $JAVA_LOCATION"
echo -n `javac -version`
echo -n `java -version`
