#!/bin/sh

SCRIPT=$0

function usage() {
    echo "Usage: $SCRIPT JAVA_LOCATION"
    echo ""
    echo "  Activate a Java version for use."
    echo ""
    echo "Arguments:"
    echo "  JAVA_LOCATION  A folder with java and javac."
    echo ""
    echo "Example:"
    echo "  $SCRIPT ~/java/jdk1.8.0_66"
}

# If no arguments, display usage.
if [ $# -eq 0 ]
then
    usage
    return 1
fi

# Parse any arguments passed in.
while [ $# -gt 0 ]
do

    case $1 in

        --help)
            usage
            return 1
            ;;

        *)
            JAVA_LOCATION=$1
            ;;
    esac
    shift

done

# Make sure $JAVA_LOCATION is a directory.
if [ ! -d $JAVA_LOCATION ]
then
    echo "'$JAVA_LOCATION' is not a valid directory."
    usage
    return 1
fi

# Make sure there's a /bin directory in $JAVA_LOCATION.
JAVA_BIN=$JAVA_LOCATION/bin
if [ ! -d $JAVA_BIN ]
then
    echo "No 'bin' in '$JAVA_LOCATION'."
    usage
    return 1
fi

# Make sure there's a `java` program in $JAVA_BIN
if [ ! -f $JAVA_BIN/java ]
then
    echo "No java in '$JAVA_BIN'"
    usage
    return 1
fi

# Make sure there's a `javac` program in $JAVA_BIN
if [ ! -f $JAVA_BIN/javac ]
then
    echo "No javac in '$JAVA_BIN'"
    usage
    return 1
fi

export PATH=$JAVA_BIN:$PATH
echo "Using $JAVA_LOCATION"
echo -n `javac -version`
echo -n `java -version`
